stages:
  - build

build:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
  before_script:
    - docker info
  script:
    - echo $ENV_LOCAL
    - cp $ENV_LOCAL .env.local
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.myusernamesthis.net:8443
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} .
    - docker image tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:latest
